name: apk
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  http: ^1.2.1
  shared_preferences: ^2.0.8
  image_picker: ^0.8.4+3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cupertino_icons: ^1.0.6
  file_picker: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/images/logo.png
    - assets/images/icone_classe.png
    - assets/images/default_avatar.jpeg
  uses-material-design: true
